name: Doc Build

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: pip3 install --user -r requirements.txt
      - run: git config --global user.email "cccccc2002@outlook.com"
      - run: git config --global user.name "horrordor"
      - run: mkdocs gh-deploy
      - run: rm -rf ./site
      - run: ls -R
